nguage: ruby
script: bundle exec rake
cache:  bundler
sudo:   false

rvm:
  - 2.2.7
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby-9.1.8.0
  - jruby-head

gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.8.0
    - rvm: jruby-head
    - gemfile: gemfiles/rails_edge.gemfile
