nguage: ruby
script: bundle exec rake test test:isolated test:integration
cache:  bundler
sudo:   false

before_install:
  openssl aes-256-cbc -K $encrypted_86ed69f44076_key -iv $encrypted_86ed69f44076_iv -in ./certs/apns_example_production.pem.enc -out certs/apns_example_production.pem -d

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
  - jruby-9.1.10.0
  - jruby-head

gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.10.0
    - rvm: jruby-head
    - gemfile: gemfiles/rails_edge.gemfile
