nguage: ruby
script: bundle exec rake test test:isolated test:integration
cache:  bundler
sudo:   false

before_install:
  - gem update --system
  - gem pristine bundler
  - openssl aes-256-cbc -K $encrypted_86ed69f44076_key -iv $encrypted_86ed69f44076_iv -in ./certs/apns_auth_key_for_jwt_auth.p8.enc -out certs/apns_auth_key_for_jwt_auth.p8 -d
  - openssl aes-256-cbc -K $encrypted_86ed69f44076_key -iv $encrypted_86ed69f44076_iv -in ./certs/apns_example_production.pem.enc -out certs/apns_example_production.pem -d

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
  - jruby-9.1.15.0
  - jruby-head

gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.13.0
    - rvm: jruby-head
    - gemfile: gemfiles/rails_edge.gemfile
